# -*- coding: utf-8 -*-
"""0629_Practice_Folium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivesO6RC2R2I7rb1w_N-V5KfLNQBB-gS
"""

import pandas as pd

forest = pd.read_csv('forest.csv', engine ='python', encoding='EUCKR')

# forest = forest.loc[forest['경도'].isnull()].dropna()
# forest[['위도', '경도']].dropna()
forest = forest.dropna(subset=["위도"])

# forest.columns
forest.isnull().sum()

sel = ['위도','경도']
temp_forest = forest[sel]
print(temp_forest)

import folium
from folium import plugins
import numpy as np 
import os

num = temp_forest.to_numpy()
# len_num =len(num)
print(num)
# print(len(num))

from folium import plugins
import math
import numpy as np

pop_ups = [str(i) for i in range(len(num))]
# print(pop_ups)
forest_map = folium.Map([35.89924607 , 127.8142083 ], zoom_start=10)
plugins.MarkerCluster(num, popups=pop_ups).add_to(m)
forest_map

forest_map.save("forest_Korea.html")

